server:
  port: 8999
  
eureka:
  instance:
    hostname: localhost
    eureka:
 
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: contact-service
        uri: lb://contact-service
        predicates:
        - Path=/contact/**
      httpclient:
        proxy:
          dns-server: 8.8.8.8
 
                                    
        
   